import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageCircle, Share2 } from "lucide-react";
import Navbar from "@/components/Navbar";
import { rides } from "@/data/rides";

export default async function ConfirmationPage({ params }: { params: Promise<{ id: string }> }) {
 const {id}=await params; const ride=rides.find(r=>r.id===id)??rides[0];
 return <><Navbar/><main className="min-h-screen bg-[#f7faf8]"><div className="container flex min-h-[calc(100vh-72px)] items-center justify-center py-12"><div className="w-full max-w-2xl rounded-[32px] border border-[#dce9e5] bg-white p-7 text-center shadow-sm sm:p-10"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#dff6ee] text-[#0f9f88]"><CheckCircle2 size={42}/></div><p className="mt-7 eyebrow">Booking confirmed</p><h1 className="mt-2 text-4xl font-black tracking-tight">You’re booked!</h1><p className="mx-auto mt-3 max-w-md text-[#607477]">Your seat is reserved. You can message {ride.driver} to coordinate the exact pickup point.</p><div className="mt-8 rounded-3xl bg-gradient-to-br from-[#e8f7f2] via-[#fffaf0] to-[#ffe8dc] p-6 text-left"><div className="flex items-center justify-between gap-4"><div><p className="text-2xl font-black">{ride.from}</p><p className="mt-1 text-sm text-[#607477]">{ride.date} · {ride.departure}</p></div><ArrowRight className="text-[#0f9f88]"/><div className="text-right"><p className="text-2xl font-black">{ride.to}</p><p className="mt-1 text-sm text-[#607477]">Arrives {ride.arrival}</p></div></div><div className="mt-6 grid gap-3 border-t border-black/5 pt-5 sm:grid-cols-3"><div><p className="text-xs text-[#607477]">Driver</p><p className="mt-1 font-bold">{ride.driver}</p></div><div><p className="text-xs text-[#607477]">Seat</p><p className="mt-1 font-bold">1 passenger</p></div><div><p className="text-xs text-[#607477]">Contribution</p><p className="mt-1 font-bold">${ride.price}</p></div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/trips" className="rido-primary rounded-xl py-3.5 text-sm font-bold">View my trips</Link><Link href="#" className="flex items-center justify-center gap-2 rounded-xl border border-[#dce9e5] py-3.5 text-sm font-bold"><MessageCircle size={16}/> Message driver</Link><button className="flex items-center justify-center gap-2 rounded-xl border border-[#dce9e5] py-3.5 text-sm font-bold"><Share2 size={16}/> Share trip</button></div></div></div></main></>
}
