'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowLeft, ArrowRight, CalendarDays, Car, Check, Clock3, MapPin, Users} from 'lucide-react';

const steps=['Route','When','Vehicle','Seats','Contribution','Review'];
export default function OfferRide(){
 const [step,setStep]=useState(0); const [from,setFrom]=useState('Austin'); const [to,setTo]=useState('Dallas');
 const [date,setDate]=useState('Sep 30, 2026'); const [time,setTime]=useState('7:00 AM'); const [seats,setSeats]=useState(2); const [price,setPrice]=useState(32);
 const next=()=>setStep(s=>Math.min(5,s+1)); const back=()=>setStep(s=>Math.max(0,s-1));
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f7faf8_0%,#fffaf0_100%)] py-10 md:py-16"><div className="container">
  <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#607477] hover:text-[#087f6e]"><ArrowLeft size={16}/> Back to Rido</Link>
  <div className="mt-8 grid gap-10 lg:grid-cols-[.7fr_1.3fr]">
   <aside className="rounded-[32px] bg-[#102c2b] p-7 text-white md:p-9"><span className="eyebrow !text-[#78dbc9]">Offer a ride</span><h1 className="mt-4 text-4xl font-black tracking-[-.05em] md:text-5xl">Turn your empty seats into a shared journey.</h1><p className="mt-5 leading-7 text-white/65">Set your route, choose your vehicle, and decide how many people can join.</p><div className="mt-9 space-y-3">{steps.map((s,i)=><div key={s} className={`flex items-center gap-3 rounded-2xl px-4 py-3 ${i===step?'bg-white/12':'text-white/45'}`}><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-black ${i<step?'bg-[#55c8b3] text-[#102c2b]':i===step?'bg-white text-[#102c2b]':'bg-white/10'}`}>{i<step?<Check size={15}/>:i+1}</span><span className="font-semibold">{s}</span></div>)}</div></aside>
   <section className="rounded-[32px] border border-[#dce9e5] bg-white p-6 shadow-[0_24px_70px_rgba(16,44,43,.08)] md:p-10">
    {step===0&&<><span className="eyebrow">Step 1</span><h2 className="mt-2 text-3xl font-black">Where are you going?</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Field label="From" icon={<MapPin size={17}/>} value={from} onChange={setFrom}/><Field label="To" icon={<MapPin size={17}/>} value={to} onChange={setTo}/></div></>}
    {step===1&&<><span className="eyebrow">Step 2</span><h2 className="mt-2 text-3xl font-black">When are you leaving?</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Field label="Date" icon={<CalendarDays size={17}/>} value={date} onChange={setDate}/><Field label="Departure time" icon={<Clock3 size={17}/>} value={time} onChange={setTime}/></div></>}
    {step===2&&<><span className="eyebrow">Step 3</span><h2 className="mt-2 text-3xl font-black">Choose your vehicle</h2><div className="mt-8 rounded-3xl border-2 border-[#0f9f88] bg-[#effaf7] p-5"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-[#0f9f88]"><Car/></span><div><p className="font-black">Toyota RAV4</p><p className="text-sm text-[#607477]">Pearl White · Comfortable · 5 seats</p></div><Check className="ml-auto text-[#0f9f88]"/></div></div><Link href="/vehicles" className="mt-4 inline-block text-sm font-bold text-[#087f6e]">Manage vehicles →</Link></>}
    {step===3&&<><span className="eyebrow">Step 4</span><h2 className="mt-2 text-3xl font-black">How many passengers can join?</h2><div className="mt-10 flex items-center justify-between rounded-3xl bg-[#f3f8f6] p-6"><div className="flex items-center gap-3"><Users className="text-[#0f9f88]"/><div><p className="font-black">Available seats</p><p className="text-sm text-[#607477]">Keep at least one seat for yourself.</p></div></div><div className="flex items-center gap-4"><button onClick={()=>setSeats(Math.max(1,seats-1))} className="grid h-10 w-10 place-items-center rounded-full bg-white font-black">−</button><span className="w-5 text-center text-xl font-black">{seats}</span><button onClick={()=>setSeats(Math.min(4,seats+1))} className="grid h-10 w-10 place-items-center rounded-full bg-white font-black">+</button></div></div></>}
    {step===4&&<><span className="eyebrow">Step 5</span><h2 className="mt-2 text-3xl font-black">Set your contribution</h2><div className="mt-8 rounded-3xl bg-[#f3f8f6] p-7"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-[#607477]">Passenger contribution</p><p className="mt-2 text-5xl font-black">${price}</p></div><span className="rounded-full bg-[#d9f5ee] px-3 py-1 text-xs font-bold text-[#087f6e]">Suggested</span></div><input className="mt-8 w-full accent-[#0f9f88]" type="range" min="20" max="60" value={price} onChange={e=>setPrice(Number(e.target.value))}/><div className="mt-2 flex justify-between text-xs text-[#809294]"><span>$20</span><span>$60</span></div></div></>}
    {step===5&&<><span className="eyebrow">Step 6</span><h2 className="mt-2 text-3xl font-black">Review your ride</h2><div className="mt-8 overflow-hidden rounded-3xl border border-[#dce9e5]"><div className="bg-[linear-gradient(135deg,#e6f6f1,#fff5df)] p-6"><div className="flex items-center justify-between"><span className="font-black">{from}</span><span className="h-px flex-1 mx-4 bg-[#7bb8ad]"/><span className="font-black">{to}</span></div></div><div className="grid gap-4 p-6 sm:grid-cols-2 text-sm"><Info icon={<CalendarDays/>} label="Date" value={date}/><Info icon={<Clock3/>} label="Departure" value={time}/><Info icon={<Car/>} label="Vehicle" value="Toyota RAV4"/><Info icon={<Users/>} label="Seats" value={`${seats} passengers`}/></div><div className="border-t border-[#dce9e5] px-6 py-5 flex items-center justify-between"><span className="font-bold">Passenger contribution</span><strong className="text-xl">${price}</strong></div></div></>}
    <div className="mt-10 flex justify-between gap-3 border-t border-[#e6efec] pt-6">{step>0?<button onClick={back} className="rounded-full border border-[#dce9e5] px-5 py-3 font-bold">Back</button>:<span/>}{step<5?<button onClick={next} className="rido-primary rounded-full px-6 py-3 font-black">Continue <ArrowRight size={17}/></button>:<button className="rido-primary-dark rounded-full px-7 py-3 font-black">Publish ride</button>}</div>
   </section>
  </div>
 </div></main>
}
function Field({label,icon,value,onChange}:{label:string;icon:React.ReactNode;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><div className="flex items-center gap-3 rounded-2xl border border-[#dce9e5] bg-[#fbfdfc] px-4 py-3 focus-within:border-[#0f9f88]"><span className="text-[#0f9f88]">{icon}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full bg-transparent outline-none"/></div></label>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-3"><span className="text-[#0f9f88]">{icon}</span><div><p className="text-xs text-[#809294]">{label}</p><p className="font-bold">{value}</p></div></div>}
